### ISSUE TITLE
代码与讲解不在一个分支

### ISSUE THREAD

**Issue by NX-Official** [Mikaelemmmm/go-zero-looklook#101]
在main分支讲解消息队列的时候，指出项目中有延迟队列

但是延迟队列的相关代码不在main分支中，而在其他分支

![image](https://user-images.githubusercontent.com/58617692/219993405-ed42ed83-3f68-4b40-9d8c-97c2d83c3672.png)

![image](https://user-images.githubusercontent.com/58617692/219993421-855c0860-b176-49ba-81c2-4bc7a9d6466a.png)

**Comment by Mikaelemmmm** [comment]
这块跟进最新代码来，但是基本都差不太多
