### ISSUE TITLE
model下的文件

### ISSUE THREAD

**Issue by heqiang** [Mikaelemmmm/go-zero-looklook#104]
用user举例，请教下，一般根据sql文件只会生成一个对应的model.go文件，里面的方法也只有增删查改那些，你这边生成的userModel_gen.go是正常生成的，userModel.go那个文件是怎么生成的啊，是要自己写吗？

**Comment by Mikaelemmmm** [comment]
> 用user举例，请教下，一般根据sql文件只会生成一个对应的model.go文件，里面的方法也只有增删查改那些，你这边生成的userModel_gen.go是正常生成的，userModel.go那个文件是怎么生成的啊，是要自己写吗？

goctl生成的哈，用最新版本的goctl就好了，带_gen是每次执行goctl生成代码会覆盖，不带_gen的 自己自定义的方法写在这里，总之使用goctl生成model，一个表会对应生成这2个文件

**Comment by heqiang** [comment]
原来如此，哈哈哈，谢谢哈，我回去升级一下最新的goctl



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月8日(周三) 中午12:13
收件人: ***@***.***&gt;;
抄送: "Qiang ***@***.******@***.***&gt;;
主题: Re: [Mikaelemmmm/go-zero-looklook] model下的文件 (Issue #104)




  
用user举例，请教下，一般根据sql文件只会生成一个对应的model.go文件，里面的方法也只有增删查改那些，你这边生成的userModel_gen.go是正常生成的，userModel.go那个文件是怎么生成的啊，是要自己写吗？
  
goctl生成的哈，用最新版本的goctl就好了，带_gen是每次执行goctl生成代码会覆盖，不带_gen的 自己自定义的方法写在这里，总之使用goctl生成model，一个表会对应生成这2个文件

**Comment by Alan-lqf** [comment]
最新的_gen文件增加了Trans这类方法，请问是通过修改模板实现的吗？之前是在不带_gen的model文件里的
