### ISSUE TITLE
windows启动docker,filebeat容器一直启动失败

### ISSUE THREAD

**Issue by hickey666** [Mikaelemmmm/go-zero-looklook#11]
报错信息：Exiting: error loading config file: config file ("filebeat.yml") must be owned by the user identifier (uid=0) or root

**Comment by Mikaelemmmm** [comment]
权限问题，把filebeat容器使用root用户 重启试一下

**Comment by hickey666** [comment]
嗯，我用的是root权限，可能还是环境的原因。我的环境是window的WSL2 Ubuntu + Windows版的docker。
我已经用  #12 解决了
