### ISSUE TITLE
deploy下的goctl模板handler.tpl在goctl的1.5.3有问题

### ISSUE THREAD

**Issue by PittYao** [Mikaelemmmm/go-zero-looklook#119]
1. windows下执行
![image](https://github.com/Mikaelemmmm/go-zero-looklook/assets/26101917/3cb8453f-a83c-4b2e-a717-8c73b1300d81)

2. 
![image](https://github.com/Mikaelemmmm/go-zero-looklook/assets/26101917/4e924b7e-de30-4218-8fa6-ac9f8785f753)
3.执行
`goctl api go -api usercenter.api -dir ../`
4.报错
![image](https://github.com/Mikaelemmmm/go-zero-looklook/assets/26101917/435abe6c-8af5-4549-88f7-df4ec67df5e4)

修改：
1.将 `{{if .After1_1_10}}"github.com/zeromicro/go-zero/rest/httpx"{{end}}` 修改为 `"github.com/zeromicro/go-zero/rest/httpx"`

**Comment by PittYao** [comment]
rpc生成报错
`goctl rpc protoc usercenter.proto --go_out=../ --go-grpc_out=../  --zrpc_out=../ --style=goZero
`
![image](https://github.com/Mikaelemmmm/go-zero-looklook/assets/26101917/ba435786-76b1-4842-9941-5f6a55a38c69)

rpc/main.tpl更新
由
```
func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	svr := server.New{{.serviceNew}}Server(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		{{.pkg}}.Register{{.service}}Server(grpcServer, svr)

		if c.Mode == service.DevMode || c.Mode == service.TestMode {
			reflection.Register(grpcServer)
		}
	})

	//rpc log
	s.AddUnaryInterceptors(rpcserver.LoggerInterceptor)

	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
} 
```

改为

```
func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
{{range .serviceNames}}       {{.Pkg}}.Register{{.Service}}Server(grpcServer, {{.ServerPkg}}.New{{.Service}}Server(ctx))
{{end}}
		if c.Mode == service.DevMode || c.Mode == service.TestMode {
			reflection.Register(grpcServer)
		}
	})

	//rpc log
	s.AddUnaryInterceptors(rpcserver.LoggerInterceptor)

	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
```

**Comment by Mikaelemmmm** [comment]
> rpc生成报错 `goctl rpc protoc usercenter.proto --go_out=../ --go-grpc_out=../ --zrpc_out=../ --style=goZero ` ![image](https://user-images.githubusercontent.com/26101917/246038032-ba435786-76b1-4842-9941-5f6a55a38c69.png)
> 
> rpc/main.tpl更新 由
> 
> ```
> func main() {
> 	flag.Parse()
> 
> 	var c config.Config
> 	conf.MustLoad(*configFile, &c)
> 	ctx := svc.NewServiceContext(c)
> 	svr := server.New{{.serviceNew}}Server(ctx)
> 
> 	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
> 		{{.pkg}}.Register{{.service}}Server(grpcServer, svr)
> 
> 		if c.Mode == service.DevMode || c.Mode == service.TestMode {
> 			reflection.Register(grpcServer)
> 		}
> 	})
> 
> 	//rpc log
> 	s.AddUnaryInterceptors(rpcserver.LoggerInterceptor)
> 
> 	defer s.Stop()
> 
> 	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
> 	s.Start()
> } 
> ```
> 
> 改为
> 
> ```
> func main() {
> 	flag.Parse()
> 
> 	var c config.Config
> 	conf.MustLoad(*configFile, &c)
> 	ctx := svc.NewServiceContext(c)
> 
> 	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
> {{range .serviceNames}}       {{.Pkg}}.Register{{.Service}}Server(grpcServer, {{.ServerPkg}}.New{{.Service}}Server(ctx))
> {{end}}
> 		if c.Mode == service.DevMode || c.Mode == service.TestMode {
> 			reflection.Register(grpcServer)
> 		}
> 	})
> 
> 	//rpc log
> 	s.AddUnaryInterceptors(rpcserver.LoggerInterceptor)
> 
> 	defer s.Stop()
> 
> 	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
> 	s.Start()
> }
> ```

可以提个pr
