### ISSUE TITLE
filebeat启动 Exiting: error loading config file: config file("filebeat.yml") can only be writable by the owner......

### ISSUE THREAD

**Issue by Mikaelemmmm** [Mikaelemmmm/go-zero-looklook#12]
filebeat启动 Exiting: error loading config file: config file("filebeat.yml") can only be writable by the owner but ther permissions are "-rwxrwxrwx" .......

**Comment by Mikaelemmmm** [comment]
解决方案 ，在docker-compose-env.yml中的filebeat加入一行即可

command: filebeat -e -strict.perms=false

禁止filebeat检查

**Comment by ericdong2012** [comment]
整个问题我开始也碰到了，主要是本地映射的文件权限问题，可通过  chmod go-w filebeat.yml  解决
