### ISSUE TITLE
grammatical error in ReadMe.md

### ISSUE THREAD

**Issue by Allen9012** [Mikaelemmmm/go-zero-looklook#122]
![image](https://github.com/Mikaelemmmm/go-zero-looklook/assets/86969944/524d9680-dd33-4d7b-bddd-2b3dab75ae3a)
There is a grammatical error in this sentence.

**Comment by Mikaelemmmm** [comment]
你可以提一个pull request吗？ thank you

**Comment by Allen9012** [comment]
got it
