### ISSUE TITLE
CommonJwtAuthMiddleware使用

### ISSUE THREAD

**Issue by a95241815** [Mikaelemmmm/go-zero-looklook#123]
我看项目里有CommonJwtAuthMiddleware的中间件，但没有用上，我使用了示例的jwt进行认证，想从header中解密出用户id放到上下文中，请问有这方面的示例吗

**Comment by Mikaelemmmm** [comment]
这个如果想用的话直接 当作middleware使用即可，就不需要使用zero默认的jwt了。
这个中间件是为了处理一种场景：
有的接口不等登陆的时候给用户返回推荐列表，如果用户登陆的话就拿用户自己的列表数据。zero默认的jwt 就是如果你配置了jwt，那么token必须通过，就无法满足这个场景

**Comment by a95241815** [comment]
好的，感谢解答
