### ISSUE TITLE
model生成问题

### ISSUE THREAD

**Issue by QianSu** [Mikaelemmmm/go-zero-looklook#129]
看了你的源码里面 usercenter的model生成了部分sql代码，但是利用gotcl model 那个指令没有生成的你userModel_gen里面的一些sql方法 如Tran session ，想问一下这些sql的方法是后期自己加上去的吗？如果是，但是gozero上说不要修改userModel_gen这些文件。如果不是，想问一下是怎么操作呢

**Comment by w22296437978** [comment]
通过修改template来自动生成的,详情查看goctl template

**Comment by Mikaelemmmm** [comment]
> 看了你的源码里面 usercenter的model生成了部分sql代码，但是利用gotcl model 那个指令没有生成的你userModel_gen里面的一些sql方法 如Tran session ，想问一下这些sql的方法是后期自己加上去的吗？如果是，但是gozero上说不要修改userModel_gen这些文件。如果不是，想问一下是怎么操作呢

使用go-zero的模板功能，looklook的模板在这里https://github.com/Mikaelemmmm/go-zero-looklook/tree/main/deploy/goctl
