### ISSUE TITLE
windows WSL2 mysql容器一直重启，报错信息...

### ISSUE THREAD

**Issue by hickey666** [Mikaelemmmm/go-zero-looklook#13]
[ERROR] [MY-010326] [Server] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist

[ERROR] [MY-010952] [Server] The privilege system failed to initialize correctly. For complete instructions on how to upgrade MySQL to a new version please see the 'Upgrading MySQL' section from the MySQL manual.

[ERROR] [MY-010119] [Server] Aborting

![image](https://user-images.githubusercontent.com/18654393/154450020-b1e1be15-df56-41e1-bebf-f87e239bd0c7.png)
这个文件里面是空的

**Comment by hickey666** [comment]
我把数据挂载去掉就好了，就不会一直重启了，貌似也是权限的问题

**Comment by Mikaelemmmm** [comment]
貌似是windows下权限的问题
