### ISSUE TITLE
关于api服务需要跑一个周期任务的问题

### ISSUE THREAD

**Issue by ren-ming** [Mikaelemmmm/go-zero-looklook#134]
大佬您好，请教一下。
我有个业务逻辑，需要每分钟更新一次数据库表的更新，并对应写了一个函数。
这个函数写在了logic里面，会使用到logic中结构体的svcCtx中的已经初始化好的db。
想做一个go func的功能一直在跑，所以想请问一下，在哪里做这个函数的初始化比较好，在svc里面初始化的话会导致相互导包的冲突

**Comment by Mikaelemmmm** [comment]
其实都可以，你写一个InitTimer，在main中启动的时候调用，传进去svcCtx就行了
