### ISSUE TITLE
请问如何方便快速调试

### ISSUE THREAD

**Issue by goluckycoding** [Mikaelemmmm/go-zero-looklook#135]
参考作者大佬的B站夜读视频：145 go-zero 实战经验分享

里面说到可以用ip+port的方式加入注册中心，判断ip的方法来进行流量的传递方向

那么我在本项目中很疑惑没有注册中心的，怎么才能把包发往tag为ip的服务呢

**Comment by Mikaelemmmm** [comment]
> 参考作者大佬的B站夜读视频：145 go-zero 实战经验分享
> 
> 里面说到可以用ip+port的方式加入注册中心，判断ip的方法来进行流量的传递方向
> 
> 那么我在本项目中很疑惑没有注册中心的，怎么才能把包发往tag为ip的服务呢

这个要自己做一下grpc负载均衡策略覆盖go-zero默认的p2c，默认go-zero不支持
