### ISSUE TITLE
很棒的项目，顺便请教一个问题

### ISSUE THREAD

**Issue by ckcfcc** [Mikaelemmmm/go-zero-looklook#136]
该项目对一直做单体应用的来说简直是帮了大忙。目前正在转微服务中

我在学习此项目的时候思考了一个问题，百撕不得骑姐。忘指点一二。

比如传统的一个项目，用户权限验证是在统一的一个地方完成的。

但是拆分成微服务后，每个api每个服务都应该要做权限，这块是否每个服务、每个api都需要自己做呢

比如，我有普通用户，订单系统维护人员，民宿维护人员，以及系统管理员，那么在以往的单体系统中，分角色和权限就可以了，在调用对应的功能的时候，在服务端路由部分通过某个中间件，就直接通过登录时取到的用户信息来判断是否可以调用，如果不能就返回4xx信息

到了微服务中，那是不是要在各个服务中各自再去判断一次？那这块不是很容易重复了嘛，每个服务中都有这么一坨代码，而且每次访问都需要处理一次。

虽然jwt每次传，带上相关信息很简单，但是感觉还是怪怪的。

我在想能不能坐在网关上呢，过了登录后，后面每次调用的时候网关就直接判断一次。

不过nginx好像不能轻松完成这个任务，看了一下目前市面上的网关，好像都没法和业务中的用户信息以及权限打交道。想了很久也不知道怎么处理这个问题好，不知是否有什么解决办法。

最后，再次感谢分享了这个让我获益良多的项目

**Comment by w22296437978** [comment]
我觉得应该是这个样子：rpc是给内部用的，http是给外部的用的，有没有权限来使用某个功能，只需要入口的api层面来处理即可

**Comment by guandeng** [comment]
服务不建议做权限校验，容易出现重复校验情况，可以引入Bff层，来做路由和鉴权

**Comment by zyx134** [comment]
应该要一个用户鉴权微服务，通过rpc调用。其他的微服务将（token、header、jwt）传给鉴权微服务，然后鉴权微服务解析用户数据返回。

**Comment by zxxsong** [comment]
我觉得可以做一个网关服务

**Comment by Mikaelemmmm** [comment]
> 该项目对一直做单体应用的来说简直是帮了大忙。目前正在转微服务中
> 
> 我在学习此项目的时候思考了一个问题，百撕不得骑姐。忘指点一二。
> 
> 比如传统的一个项目，用户权限验证是在统一的一个地方完成的。
> 
> 但是拆分成微服务后，每个api每个服务都应该要做权限，这块是否每个服务、每个api都需要自己做呢
> 
> 比如，我有普通用户，订单系统维护人员，民宿维护人员，以及系统管理员，那么在以往的单体系统中，分角色和权限就可以了，在调用对应的功能的时候，在服务端路由部分通过某个中间件，就直接通过登录时取到的用户信息来判断是否可以调用，如果不能就返回4xx信息
> 
> 到了微服务中，那是不是要在各个服务中各自再去判断一次？那这块不是很容易重复了嘛，每个服务中都有这么一坨代码，而且每次访问都需要处理一次。
> 
> 虽然jwt每次传，带上相关信息很简单，但是感觉还是怪怪的。
> 
> 我在想能不能坐在网关上呢，过了登录后，后面每次调用的时候网关就直接判断一次。
> 
> 不过nginx好像不能轻松完成这个任务，看了一下目前市面上的网关，好像都没法和业务中的用户信息以及权限打交道。想了很久也不知道怎么处理这个问题好，不知是否有什么解决办法。
> 
> 最后，再次感谢分享了这个让我获益良多的项目

你可以看下1.0的tag，有个公共的identity认证服务，是在nignx中调用这个服务的，通过才会走下游业务，只是后来被我调整了

**Comment by ckcfcc** [comment]
感谢各位的回复，用网关做权鉴的思想已经了解了。再次感谢。
关闭当前issue
