### ISSUE TITLE
prometheus 的数据不是存储在 elasticsearch 中的吧

### ISSUE THREAD

**Issue by eleven26** [Mikaelemmmm/go-zero-looklook#140]
<img width="400" alt="image" src="https://github.com/Mikaelemmmm/go-zero-looklook/assets/10000532/75718990-5648-4a70-8cbb-be336ff7153d">

我看这个图中，prometheus 指向了 elasticsearch

**Comment by Mikaelemmmm** [comment]
可以配置的，本地、InfluxDB 都行
