### ISSUE TITLE
如何升级项目中的模板 1.5.3.zip为1.6.*.zip呢? 

### ISSUE THREAD

**Issue by iwhy** [Mikaelemmmm/go-zero-looklook#142]
我本地使用的goctl是1.6.1的.  
目前新生成的model的代码中, 方法少了好多.  

因此 想问一下, 如何把go-zero-looklook提供的模板1.5.3升级到1.6.1呢? 
大致都需要修改哪些文件?
是只需要需改.goctl\1.6.1\model下的文件吗, 还是 整个模板文件都有改动?

谢谢!

**Comment by Mikaelemmmm** [comment]
基本就是改 .goctl\1.6.1\model 这个就行了，model文件夹是生成db model代码使用的模板，其他模块一般很少改动。你可以使用goctl(1.6.1版本) template init， 然后根据looklook1.5.1模板下model粘贴过去稍微调整一下就行了，一般改动不会太大
