### ISSUE TITLE
[Question] 请问api和rpc业务功能上设计的考虑?

### ISSUE THREAD

**Issue by wymli** [Mikaelemmmm/go-zero-looklook#15]
# Question
请问在设计上,哪些logic要放在api,哪些logic要放在rpc呢?  
以`travel api`为例, 
1. 对于其他路径, 处理逻辑都是自己读db或计算
2. 对于`/homestayDetail`路径,它会转发给`travel rpc`处理,然后`travel rpc`会读db

我比较疑惑的是处理逻辑放在api还是rpc是怎么考虑的呢?  

看调用拓扑图,rpc还会被其他api调用,那么是将那些可能被其他api所调用的功能放在rpc来复用吗? 可是判断哪些功能会被复用,以及后续的增减似乎并不轻松.   
# Background
我此前的理解是所有服务都使用rpc来编写,同时使用`grpc-gateway`来生成grpc的http代理,可以一个`rpc server`一个`grpc gateway`,然后使用一个nginx来反向代理所有的gateway,也可以多个`rpc server`一个`grpc gateway`,gateway本身就充当nginx网关的反向代理功能.   

这样的好处是对于`rpc`和`http rest`,我只需要维护一个proto文件就可以了. 在gozero中,api和pb是需要分别定义的,但在事实实践上,api的定义和pb的定义又基本是一致的,但却需要定义两次,所以这个会让我比较困惑.  

不过看了本仓库,倒是解决了我这个困惑,那就是api并不是rpc的一个协议转换代理,但也引出了上面的第一个问题,哪些logic要放在api,哪些logic要放在rpc呢?
  
感谢解答!

**Comment by Mikaelemmmm** [comment]
yes ,   其实公用的业务（比如后后台api、其他rpc、api都有用到的业务方法）写到rpc中然后在通过api、rpc、admin各自去调用，如果不涉及到公用一些简单的前端接口自己用到的业务可以直接在api中写就不需要在多一道api->rpc调用过程了，但是他们最终都是操作的一个model即可
