### ISSUE TITLE
m1芯片的macOS无法运行的问题，mysql报错的。

### ISSUE THREAD

**Issue by starwu** [Mikaelemmmm/go-zero-looklook#18]
`Pulling mysql (mysql:8.0.24)...

8.0.24: Pulling from library/mysql

ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by starwu** [comment]
这个需要到hub.docker去找支持arm64的mysql镜像。
image: mysql/mysql-server:8.0.28   #m1的芯片无法启动，换这个
然后就可以了。

宿主机需要通过127.0.0.1:33069登录mysql还需要去放行root账号的权限；
将root的localhost改为%即可；

`
dc exec -it mysql /bin/bash
bash-4.4# mysql -h 127.0.0.1 -P 3306 -uroot -p
Enter password:
ERROR 1130 (HY000): Host '127.0.0.1' is not allowed to connect to this MySQL server
bash-4.4# mysql -uroot -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 203
Server version: 8.0.28 MySQL Community Server - GPL

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed

mysql> select user,host from user;
+------------------+-----------+
| user             | host      |
+------------------+-----------+
| healthchecker    | localhost |
| mysql.infoschema | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
| root             | localhost |
+------------------+-----------+
5 rows in set (0.00 sec)

mysql> update user set host = '%' where user = 'root';
Query OK, 1 row affected (0.05 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select user,host from user;
+------------------+-----------+
| user             | host      |
+------------------+-----------+
| root             | %         |
| healthchecker    | localhost |
| mysql.infoschema | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
+------------------+-----------+
5 rows in set (0.00 sec)

`

**Comment by starwu** [comment]
> `Pulling mysql (mysql:8.0.24)...
> 
> 8.0.24: Pulling from library/mysql
> 
> ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries`

这个需要到hub.docker去找支持arm64的mysql镜像。
image: mysql/mysql-server:8.0.28 #m1的芯片无法启动，换这个
然后就可以了。

宿主机需要通过127.0.0.1:33069登录mysql还需要去放行root账号的权限；
将root的localhost改为%即可；

`
dc exec -it mysql /bin/bash
bash-4.4# mysql -h 127.0.0.1 -P 3306 -uroot -p
Enter password:
ERROR 1130 (HY000): Host '127.0.0.1' is not allowed to connect to this MySQL server
bash-4.4# mysql -uroot -p
Enter password:
Welcome to the MySQL monitor. Commands end with ; or \g.
Your MySQL connection id is 203
Server version: 8.0.28 MySQL Community Server - GPL

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed

mysql> select user,host from user;
+------------------+-----------+
| user | host |
+------------------+-----------+
| healthchecker | localhost |
| mysql.infoschema | localhost |
| mysql.session | localhost |
| mysql.sys | localhost |
| root | localhost |
+------------------+-----------+
5 rows in set (0.00 sec)

mysql> update user set host = '%' where user = 'root';
Query OK, 1 row affected (0.05 sec)
Rows matched: 1 Changed: 1 Warnings: 0

mysql> select user,host from user;
+------------------+-----------+
| user | host |
+------------------+-----------+
| root | % |
| healthchecker | localhost |
| mysql.infoschema | localhost |
| mysql.session | localhost |
| mysql.sys | localhost |
+------------------+-----------+
5 rows in set (0.00 sec)

`

**Comment by Mikaelemmmm** [comment]
或者加tag，之前在issue中有提到
