### ISSUE TITLE
 关于cosmtrek/air 使用的疑问

### ISSUE THREAD

**Issue by waltcow** [Mikaelemmmm/go-zero-looklook#20]
在开发过程中遇到rpc的service 容器recreate的情况，这时候容器会重新下载一遍依赖，
加上了 `GOPROXY: https://goproxy.cn,direct` 一样很慢
这个能不能做一下缓存策略

![image](https://user-images.githubusercontent.com/3941174/155652960-3bb279b3-3c60-46f8-9550-a4b9dbb68bc8.png)

**Comment by waltcow** [comment]
期待一下modd 的相关实践

**Comment by godsoul** [comment]
一直卡在 go: downloading sigs.k8s.io/yaml  容器起来不起来，这太多镜像一起拉依赖了，每次还得重新拉一遍
