### ISSUE TITLE
1.3.0-cli/model/insert.tpl中的一个缺省，导致模板替换无法生成modle内容

### ISSUE THREAD

**Issue by shitou7988** [Mikaelemmmm/go-zero-looklook#21]
func (m *default{{.upperStartCamelObject}}Model) Insert(session sqlx.Session, data *{{.upperStartCamelObject}}) (sql.Result,error) {
	{{if .withCache}}{{if .containsIndexCache}}{{.keys}}
    return m.Exec(func(conn sqlx.SqlConn) (result sql.Result, err error) {
		//@todo self edit  value , because change table field is trouble in here , so self fix field is easy
		//query := fmt.Sprintf("insert into %s (...) values (...)  m.table)
               query := fmt.Sprintf("insert into %s (...) values (...)",  m.table)

		if session != nil{
			//@todo self edit  value , because change table field is trouble in here , so self fix field is easy
			return session.Exec(query,{{.expressionValues}})
		}
		//@todo self edit  value , because change table field is trouble in here , so self fix field is easy
		return conn.Exec(query, {{.expressionValues}})
	}, {{.keyValues}}){{else}}
	//@todo self edit  value , because change table field is trouble in here , so self fix field is easy
	query := fmt.Sprintf("insert into %s (....) values (...)", m.table)
	if session != nil{
		//@todo self edit  value , because change table field is trouble in here , so self fix field is easy
	   return session.Exec(query, {{.expressionValues}})
	}
	//@todo self edit  value , because change table field is trouble in here , so self fix field is easy
    return m.ExecNoCache(query, {{.expressionValues}})
	{{end}}{{else}}
	//@todo self edit  value , because change table field is trouble in here , so self fix field is easy
	query := fmt.Sprintf("insert into .... (%s) values ...", m.table)
	if session != nil{
		//@todo self edit  value , because change table field is trouble in here , so self fix field is easy
		return session.Exec(query,{{.expressionValues}})
	}
	//@todo self edit  value , because change table field is trouble in here , so self fix field is easy
	return m.conn.Exec(query, {{.expressionValues}})
	{{end}}
}

**Comment by Mikaelemmmm** [comment]
这个可以自己替换
