### ISSUE TITLE
搭建开发环境常见问题解决方案

### ISSUE THREAD

**Issue by Mikaelemmmm** [Mikaelemmmm/go-zero-looklook#25]
创建阶段，起docker-compose-env.yml容器
Grafana 报错You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
因权限问题导致，可在docker-compose-env.yml中grafana部分加入user: root

filebeat容器启动报错Exiting: error loading config file: config file ("filebeat.yml") must be owned by the user identifier (uid=0) or root
因文件所有者不同导致（我在普通用户下clone的项目），filebeat的配置文件所有者必须为root，需修改sudo chown root deploy/filebeat/conf/filebeat.yml 

elasticsearch容器启动报错ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
报错原因es没有权限操作挂载目录，无法绑定节点，解决方法，修改权限sudo chmod 777 data/elasticsearch/data （不知道es是哪个用户启动的，所以硬改了777）

jaeger依赖于elasticsearch，且没有失败自动重启

**Comment by Mikaelemmmm** [comment]
欢迎其他小伙伴，一起提交遇到的问题，一起支持开源

**Comment by gocpplua** [comment]
> 欢迎其他小伙伴，一起提交遇到的问题，一起支持开源

感谢，es出现错误： "stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
 
修改权限就行了 sudo chmod 777 data/elasticsearch/data
