### ISSUE TITLE
本地安装go语言版本低于1.17时启动报错

### ISSUE THREAD

**Issue by yuanybin** [Mikaelemmmm/go-zero-looklook#28]
当本地go版本低于1.17时，在本地执行go mod tidy之后，执行docker-compose up之后报错：
![image](https://user-images.githubusercontent.com/26023465/157661590-8195fc0b-81f0-4702-a62b-8df448884273.png)
升级本地go版本，或者在容器中重新执行go mod tidy之后方可build成功

**Comment by Mikaelemmmm** [comment]
建议升级golang ，保持版本容器内部跟本地一直
