### ISSUE TITLE
所有服务都启动起来了，但是looklook容器CPU占用一直下不来

### ISSUE THREAD

**Issue by luokuncool** [Mikaelemmmm/go-zero-looklook#29]
所有服务都启动起来了，但是looklook容器CPU占用一直下不来，一直维持在20%以上 
 
![image](https://user-images.githubusercontent.com/6022635/157790806-8c8dba93-aa7a-4ef4-ac0e-e36e7659c861.png)

会不会和looklook的镜像是arm架构的原因呢？
 
![image](https://user-images.githubusercontent.com/6022635/157790890-2ba12432-009f-442c-a1b7-e59d6669ac2d.png)

**Comment by Mikaelemmmm** [comment]
打了新amd镜像，如果m1推荐使用arm，更新代码可以看一下

**Comment by luokuncool** [comment]
更新了代码，现在报这个错了
```
11:48:01: prep: go build -o data/server/order-mq  -v app/order/cmd/mq/order.go
app/payment/model/thirdPaymentModel.go:6:2: package looklook/deploy/script/mysql/genModel is not in GOROOT (/usr/local/go/src/looklook/deploy/script/mysql/genModel)
exit status 1
```
![image](https://user-images.githubusercontent.com/6022635/157798483-a11329f1-4101-44f3-b1cf-4914fde0c1aa.png)
