### ISSUE TITLE
报错: package looklook/deploy/script/mysql/genModel is not in GOROOT (/usr/local/go/src/looklook/deploy/script/mysql/genModel)

### ISSUE THREAD

**Issue by jialeo** [Mikaelemmmm/go-zero-looklook#30]
```
app/payment/model/thirdPaymentModel.go:6:2: package looklook/deploy/script/mysql/genModel is not in GOROOT (/usr/local/go/src/looklook/deploy/script/mysql/genModel)
```

![image](https://user-images.githubusercontent.com/8233510/157820823-41349ac5-004e-4913-9e21-e17e9a688b1f.png)

<img width="919" alt="image" src="https://user-images.githubusercontent.com/8233510/157821052-711566e2-516c-49b1-b848-8a0b9e87bd2a.png">

**Comment by Mikaelemmmm** [comment]
已修复了 更新下代码
