### ISSUE TITLE
提供的goctl模版 生成出错了

### ISSUE THREAD

**Issue by waltcow** [Mikaelemmmm/go-zero-looklook#31]
提供的goctl模版 生成出错了，详情如下图

![image](https://user-images.githubusercontent.com/3941174/157831175-7d24de93-d0cc-4bf9-b354-eadacd7b9c3b.png)

**Comment by Mikaelemmmm** [comment]
直接把这个ModelBuilder删了就行了 ，没用这个，或者更新一下代码 这个已经修复了

**Comment by Mikaelemmmm** [comment]
1.3.2.zip模版压缩包内容已经替换了

**Comment by waltcow** [comment]
是的，建议模版分出一个repo单独维护
