### ISSUE TITLE
按照文档在搭建开发环境中设置es索引填写looklook-* 无法点击Next Step

### ISSUE THREAD

**Issue by jaguarWang** [Mikaelemmmm/go-zero-looklook#33]

**Comment by Mikaelemmmm** [comment]
先按照文档说明的 ，去kafka容器内部控制台消费一下looklook-log，确认下是否收集到了kafka，如果收集到了，重启一下go-stash 稍等1分钟再看

**Comment by jaguarWang** [comment]
谢谢大佬耐心排查，最终确实重启下go-stash问题解决。

**Comment by gocpplua** [comment]
> 去kafka容器内部控制台消费

你好，我现在go-stach 无法连接kafka和es，这个问题遇到过吗
