### ISSUE TITLE
casbin验权的问题

### ISSUE THREAD

**Issue by starwu** [Mikaelemmmm/go-zero-looklook#37]
线上的casbin，一般是怎么应用的？
参考looklook项目，想加入casbin的验权功能，有几个问题想听听大佬的分析？
1. 如果各个独立的微服务的api里面使用中间件引入casbin，这样做需要各个app需要使用同一个数据库里面的casbin_rule表，与一个app一个库文件背道而驰了？有什么好的方法？
2. 或者在identity-api里面加casbin_rulle中间件，在nginx的auth_request这个层面就把RBAC验权给办了？
3. 重要业务的微服务app如何单独验权？比如说订单服务app，需要验证这个订单的所属用户ID；验证订单所属商家租户的id等等？

**Comment by Mikaelemmmm** [comment]
不是太清楚，这个可能跟你们业务牵扯比较多

**Comment by bigrocs** [comment]
我是这样想 通过config配置各个路由是否验权  然后中间件 调用casbin的LoadPolicy。  casbin的数据库需要通过config单独配置

go-zero路由好像还不支持单独 验权
