### ISSUE TITLE
token鉴权的问题

### ISSUE THREAD

**Issue by ImJerryChan** [Mikaelemmmm/go-zero-looklook#4]
hello，想问下什么情况下会调用nginx的/auth的路由？ 可以大概举个例子么，方法我是看懂了，但是实际的应用场景可能还不清楚，谢谢

**Comment by Mikaelemmmm** [comment]
看这篇文档 ： https://github.com/Mikaelemmmm/go-zero-looklook/blob/main/doc/2%E3%80%81nginx%E7%BD%91%E5%85%B3.md

**Comment by Mikaelemmmm** [comment]
https://github.com/Mikaelemmmm/go-zero-looklook/blob/main/doc/2%E3%80%81nginx%E7%BD%91%E5%85%B3.md
