### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by mrmm** [Mikaelemmmm/go-zero-looklook#40]
Hello,

Thank you so much for dedicating the time to create this project, the issue is that it is very hard to work with go-zero because there are so few English resources available.

Is there a way to create the documentation in English also so that it can reach more of the community 🙏 

Please let me know how I can help

**Comment by Mikaelemmmm** [comment]
Thank you very much for your email. 
I want to make a complete English document, but my English level is not very good. 
If I do, I may rely on Google translation, but I'm afraid it's not so accurate


On 04/1/2022 20:10，Mourad ***@***.***> wrote：

Hello,

Thank you so much for dedicating the time to create this project, the issue is that it is very hard to work with go-zero because there are so few English resources available.

Is there a way to create the documentation in English also so that it can reach more of the community 🙏

Please let me know how I can help

**Comment by Mikaelemmmm** [comment]
What instant messaging software do you have that we can add for communication?




On 04/1/2022 20:10，Mourad ***@***.***> wrote：

Hello,

Thank you so much for dedicating the time to create this project, the issue is that it is very hard to work with go-zero because there are so few English resources available.

Is there a way to create the documentation in English also so that it can reach more of the community 🙏

Please let me know how I can help

**Comment by mrmm** [comment]
> What instant messaging software do you have that we can add for communication? On 04/1/2022 20:10，Mourad ***@***.***> wrote： Hello, Thank you so much for dedicating the time to create this project, the issue is that it is very hard to work with go-zero because there are so few English resources available. Is there a way to create the documentation in English also so that it can reach more of the community 🙏 Please let me know how I can help — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hello  @Mikaelemmmm thanks for the quick response, I am willing to dedicate the time to help with the translation however I can.

I am on Telegram and Signal, let me know if that works for you 🙏  !

**Comment by Mikaelemmmm** [comment]
> 



> > What instant messaging software do you have that we can add for communication? On 04/1/2022 20:10，Mourad _**@**_._**> wrote： Hello, Thank you so much for dedicating the time to create this project, the issue is that it is very hard to work with go-zero because there are so few English resources available. Is there a way to create the documentation in English also so that it can reach more of the community 🙏 Please let me know how I can help — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> Hello @Mikaelemmmm thanks for the quick response, I am willing to dedicate the time to help with the translation however I can.
> 
> I am on Telegram and Signal, let me know if that works for you 🙏 !

WhatsAPP ?

**Comment by Mikaelemmmm** [comment]
> > What instant messaging software do you have that we can add for communication? On 04/1/2022 20:10，Mourad _**@**_._**> wrote： Hello, Thank you so much for dedicating the time to create this project, the issue is that it is very hard to work with go-zero because there are so few English resources available. Is there a way to create the documentation in English also so that it can reach more of the community 🙏 Please let me know how I can help — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> Hello @Mikaelemmmm thanks for the quick response, I am willing to dedicate the time to help with the translation however I can.
> 
> I am on Telegram and Signal, let me know if that works for you 🙏 !

okok ， I can add your telegram. If it's inconvenient for you to disclose your telegram account, you can send me a separate email to your telegram account, and I'll add you

**Comment by mrmm** [comment]
@Mikaelemmmm My telegram account is `@ ronittos`  let me know when you have added 🙏

**Comment by Mikaelemmmm** [comment]
> @Mikaelemmmm My telegram account is `@ ronittos` let me know when you have added 🙏

Sorry, I found that my telegram does not work very well ~ ~ ~, recently I will organize a set of English documents, thank you for your advice

**Comment by mrmm** [comment]
> > @Mikaelemmmm My telegram account is `@ ronittos` let me know when you have added 🙏
> 
> Sorry, I found that my telegram does not work very well ~ ~ ~, recently I will organize a set of English documents, thank you for your advice

No worries, I am on **GoZero** discord too if you are there we can chat 🙏

**Comment by Mikaelemmmm** [comment]
> > > @Mikaelemmmm My telegram account is `@ ronittos` let me know when you have added 🙏
> > 
> > 
> > Sorry, I found that my telegram does not work very well ~ ~ ~, recently I will organize a set of English documents, thank you for your advice
> 
> No worries, I am on **GoZero** discord too if you are there we can chat 🙏

hi , english doc : https://github.com/Mikaelemmmm/go-zero-looklook/tree/main/doc/english , If you think this project is good you can recommend it to people around you, help point a star, thanks for your support!

**Comment by mrmm** [comment]
Thanks a lot for your reactivity, I have been discussing with @ kevwan  on discord. We can chat if you want.
I will close this issue as it is not relevant anymore 🙏 

Thanks again

**Comment by Spuxy** [comment]
Are we going to get English subtitles/transcription ? :) Maybe via transcription from PyTorch
