### ISSUE TITLE
If the memory of notebook computer is less than 8g, can there be a simplified version of running demo

### ISSUE THREAD

**Issue by chaggle** [Mikaelemmmm/go-zero-looklook#42]

**Comment by aonoa** [comment]
应该可以的，你部署的时候可以用minikebu代替k8s集群，然后使用脚本生成服务的docker镜像，这样可以省掉gitlab、jenkins、harbor的部署，然后服务的话，可以只启动identity-api、identity-rpc、usercenter-api、usercenter-rpc这4个，这样，asynqmon消息队列也可以省掉

**Comment by Mikaelemmmm** [comment]
云服务器，centos ， 2核4g都能跑

**Comment by Mikaelemmmm** [comment]
> 应该可以的，你部署的时候可以用minikebu代替k8s集群，然后使用脚本生成服务的docker镜像，这样可以省掉gitlab、jenkins、harbor的部署，然后服务的话，可以只启动identity-api、identity-rpc、usercenter-api、usercenter-rpc这4个，这样，asynqmon消息队列也可以省掉

对的

**Comment by chaggle** [comment]
> 应该可以的，你部署的时候可以用minikebu代替k8s集群，然后使用脚本生成服务的docker镜像，这样可以省掉gitlab、jenkins、harbor的部署，然后服务的话，可以只启动identity-api、identity-rpc、usercenter-api、usercenter-rpc这4个，这样，asynqmon消息队列也可以省掉

好的，感谢您！

**Comment by chaggle** [comment]
> 云服务器，centos ， 2核4g都能跑

了解，马上搞一台2核4g服务器。目前手上只有一个1核2g的服务器！
