### ISSUE TITLE
【安装环境】导入mysql数据执行出错

### ISSUE THREAD

**Issue by gocpplua** [Mikaelemmmm/go-zero-looklook#54]
环境:
python -V -> Python 3.7.10
python3 -V -> Python 3.5.2
redis-cli 6.2.6
etcd Version: 3.5.2
Docker version 18.09.7, build 2d0083d
mysql  Ver 14.14 Distrib 5.7.33
Linux Version: Ubuntu 16.04

我在操作3.2导入mysql数据的时候， 执行:docker exec -it mysql mysql -uroot -p 失败。
执行 docker logs --tail 50 --follow --timestamps 2f48f1f5d8b8      注: 2f48f1f5d8b8 是容器id
查看docker日志发现： 
[Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
[Server] /usr/sbin/mysqld (mysqld 8.0.28) initializing of server in progress as process 16
[Server] Can't find error-message file '/usr/share/mysql-8.0/errmsg.sys'. Check error-message file location and 'lc-messages-dir' configuration directive.
[Server] Can't change data directory owner to mysql
[Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
[Server] Aborting
[Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.28)  MySQL Community Server - GPL.

请问这个如何处理？

**Comment by gocpplua** [comment]
方法一:【失败】
1. docker-compose -f docker-compose-env.yml stop mysql
2. docker-compose -f docker-compose-env.yml rm mysql
3. docker-compose -f docker-compose-env.yml create mysql
4. docker-compose -f docker-compose-env.yml start mysql
5. sudo chown -R mysql.mysql  data/mysql/data
6. docker exec -it mysql mysql -uroot -p
执行上面6个步骤，还是出问题： [Server] Can't change data directory owner to mysql

**Comment by gocpplua** [comment]
方法二：【失败】
1. 修改docker-compose-env.yml，添加 user: root
2. docker-compose -f docker-compose-env.yml stop mysql
3. docker-compose -f docker-compose-env.yml rm mysql
4. docker-compose -f docker-compose-env.yml create mysql
5. docker-compose -f docker-compose-env.yml start mysql
6. docker exec -it mysql mysql -uroot -p
执行上面6个步骤，还是出问题： [Server] Can't change data directory owner to mysql

**Comment by gocpplua** [comment]
方法三： 【成功】
1. mysql的镜像替换为 image: mysql:8.0.28
2. docker-compose -f docker-compose-env.yml stop mysql
3. docker-compose -f docker-compose-env.yml rm mysql
4. docker-compose -f docker-compose-env.yml create mysql
5. docker-compose -f docker-compose-env.yml start mysql
6. docker exec -it mysql mysql -uroot -p

**Comment by luweiqianyi** [comment]
2023-08-14 16:43:29 2023-08-14T08:43:29.296067Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
2023-08-14 16:43:29 2023-08-14T08:43:29.296084Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
2023-08-14 16:43:29 2023-08-14T08:43:29.296430Z 0 [ERROR] [MY-010119] [Server] Aborting



还是有问题啊 mysql容器启动不了
