### ISSUE TITLE
【安装环境】查看服务环境 Grafana  失败

### ISSUE THREAD

**Issue by gocpplua** [Mikaelemmmm/go-zero-looklook#55]
环境:
python -V -> Python 3.7.10
python3 -V -> Python 3.5.2
redis-cli 6.2.6
etcd Version: 3.5.2
Docker version 18.09.7, build 2d0083d
mysql Ver 14.14 Distrib 5.7.33
Linux Version: Ubuntu 16.04

在查看服务环境的时候， Elastic，jaeger等都正确，但是查看Grafana: http://127.0.0.1:3001/ 出错了，
查看日志 docker logs grafana :
t=2022-04-26T17:12:50+0800 lvl=eror msg="Failed to get settings" logger=context userId=0 orgId=0 uname= error="unable to open database file: no such file or directory"

t=2022-04-26T17:12:50+0800 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=500 remote_addr=172.18.0.1 time_ms=12 size=1728 referer=http://127.0.0.1:3001/login

浏览器输出: 
GET http://127.0.0.1:3001/login 500 (Internal Server Error)

看了项目的issues以及Google，还是没解决，请问有小伙伴遇到过吗？

**Comment by gocpplua** [comment]
详细日志:
$ docker logs grafana 
WARNING: Error loading config file: /home/SENSETIME/chenqi1/.docker/config.json: stat /home/SENSETIME/chenqi1/.docker/config.json: permission denied
t=2022-04-26T11:09:23+0800 lvl=info msg="Starting Grafana" logger=server version=8.0.6 commit=68fe9e3431 branch=HEAD compiled=2021-07-15T15:49:19+0800
t=2022-04-26T11:09:23+0800 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2022-04-26T11:09:23+0800 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2022-04-26T11:09:23+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2022-04-26T11:09:23+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2022-04-26T11:09:23+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2022-04-26T11:09:23+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2022-04-26T11:09:23+0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2022-04-26T11:09:23+0800 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
t=2022-04-26T11:09:23+0800 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
t=2022-04-26T11:09:23+0800 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
t=2022-04-26T11:09:23+0800 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
t=2022-04-26T11:09:23+0800 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2022-04-26T11:09:23+0800 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2022-04-26T11:09:23+0800 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2022-04-26T11:09:23+0800 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2022-04-26T11:09:23+0800 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2022-04-26T11:09:23+0800 lvl=info msg="App mode production" logger=settings
t=2022-04-26T11:09:23+0800 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2022-04-26T11:09:23+0800 lvl=info msg="Starting DB migrations" logger=migrator
t=2022-04-26T11:09:23+0800 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=330 duration=933.087µs
t=2022-04-26T11:09:23+0800 lvl=info msg="Starting plugin search" logger=plugins
t=2022-04-26T11:09:23+0800 lvl=info msg="Registering plugin" logger=plugins id=grafana-plugin-admin-app
t=2022-04-26T11:09:23+0800 lvl=info msg="Registering plugin" logger=plugins id=input
t=2022-04-26T11:09:23+0800 lvl=info msg="Live Push Gateway initialization" logger=live.push_http
t=2022-04-26T11:09:23+0800 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2022-04-26T11:39:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T11:49:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T11:59:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T12:09:23+0800 lvl=eror msg="failed to run garbage collect" logger=remotecache.database error="unable to open database file: no such file or directory"
t=2022-04-26T12:09:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T12:19:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T12:29:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T12:39:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T12:49:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T12:59:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T13:09:23+0800 lvl=eror msg="failed to run garbage collect" logger=remotecache.database error="unable to open database file: no such file or directory"
t=2022-04-26T13:09:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T13:19:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T13:29:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T13:39:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T13:49:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T13:59:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T14:09:23+0800 lvl=eror msg="Failed to delete expired snapshots" logger=cleanup error="unable to open database file: no such file or directory"
t=2022-04-26T14:09:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T14:19:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T14:29:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T14:39:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T14:49:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T14:59:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="attempt to write a readonly database"
t=2022-04-26T15:09:23+0800 lvl=eror msg="Failed to delete expired snapshots" logger=cleanup error="unable to open database file: no such file or directory"
t=2022-04-26T15:09:23+0800 lvl=eror msg="Failed to delete expired dashboard versions" logger=cleanup error="unable to open database file: no such file or directory"
t=2022-04-26T15:09:23+0800 lvl=eror msg="Problem expiring user invites" logger=cleanup error="unable to open database file: no such file or directory"
t=2022-04-26T15:09:23+0800 lvl=eror msg="Problem deleting stale short urls" logger=cleanup error="unable to open database file: no such file or directory"
t=2022-04-26T15:09:23+0800 lvl=eror msg="Failed to get system stats" logger=metrics error="unable to open database file: no such file or directory"
t=2022-04-26T15:09:23+0800 lvl=eror msg="failed to lock and execute cleanup of old login attempts" logger=cleanup error="unable to open database file: no such file or directory"
t=2022-04-26T15:09:23+0800 lvl=eror msg="failed to lock and execute cleanup of expired auth token" logger=auth error="unable to open database file: no such file or directory"
t=2022-04-26T15:09:24+0800 lvl=eror msg="Could not load alerts" logger=alerting.ruleReader error="unable to open database file: no such file or directory"
t=2022-04-26T15:09:34+0800 lvl=eror msg="Could not load alerts" logger=alerting.ruleReader error="unable to open database file: no such file or directory"

**Comment by Mikaelemmmm** [comment]
permission denied ， 兄弟 你环境权限这些要好好看一下了
