### ISSUE TITLE
用户对数据的权限验证如何处理，都写在logic中么

### ISSUE THREAD

**Issue by hp66722667** [Mikaelemmmm/go-zero-looklook#60]
例如api-order-UserHomestayOrderDetail，如果用户查看的订单信息并不属于该用户，这部分权限验证的逻辑直接写在logic中，还是中间件中好一点呢

**Comment by Mikaelemmmm** [comment]
> 例如api-order-UserHomestayOrderDetail，如果用户查看的订单信息并不属于该用户，这部分权限验证的逻辑直接写在logic中，还是中间件中好一点呢

建议查询时候带上用户id 即可
