### ISSUE TITLE
环境配置问题go-stash: connect: connection refused: no Elasticsearch node available

### ISSUE THREAD

**Issue by gocpplua** [Mikaelemmmm/go-zero-looklook#61]
ubuntu16.04, 参考looklook搭建自己服务环境，现在使用docker logs查看 kafka日志，发现错误：
[2022-05-20 12:04:14,070] WARN [Controller id=1001, targetBrokerId=1001] Connection to node 1001 (cloudxr-kafka/172.80.0.8:49092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

端口我用49092，改回9092, 就可以了。 但是我我的go-stash容器一直没有启动成功，错误日志如下：
2022/05/20 15:13:23 stash.go:57 health check timeout: Head "http://127.0.0.1:9200": dial tcp 127.0.0.1:9200: connect: connection refused: no Elasticsearch node available
2022/05/20 15:13:23 {"@timestamp":"2022-05-20T15:13:23.464+08","level":"fatal","content":"stash.go:57 health check timeout: Head \"http://127.0.0.1:9200\": dial tcp 127.0.0.1:9200: connect: connection refused: no Elasticsearch node available"}。

我的配置如下：
  
  #zookeeper是kafka的依赖
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: cloudxr-zookeeper
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 42181:2181
    networks:
      - cloudxr

  #消息队列
  kafka:
    image: wurstmeister/kafka
    container_name: cloudxr-kafka
    ports:
      - 9092:9092 # TCP
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=cloudxr-kafka
      - KAFKA_ZOOKEEPER_CONNECT=cloudxr-zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cloudxr
    depends_on:
      - zookeeper

  #收集业务数据
  filebeat:
    image: elastic/filebeat:7.13.4
    container_name: cloudxr-filebeat
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    user: root
    restart: always
    entrypoint: "filebeat -e -strict.perms=false"  #解决配置文件权限问题
    volumes:
      - ./deploy/filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # 此处需指定docker的containers目录，取决于你docker的配置
      # 如snap安装的docker，则为/var/snap/docker/common/var-lib-docker/containers
      # - /var/snap/docker/common/var-lib-docker/containers:/var/lib/docker/containers
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - cloudxr
    depends_on:
      - kafka

#搜集kafka业务日志、存储prometheus监控数据
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: cloudxr-elasticsearch
    user: root
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Shanghai
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    restart: always
    ports:
    - 9200:9200
    - 9300:9300
    networks:
      - cloudxr

  #消费kafka中filebeat收集的数据输出到es
  go-stash:
    image: kevinwan/go-stash:1.0 # if you "macOs intel" or "linux amd"
    container_name: cloudxr-go-stash
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    user: root
    restart: always
    volumes:
      - ./deploy/go-stash/etc:/app/etc
    networks:
      - cloudxr
    depends_on:
      - elasticsearch
      - kafka

  #查看elasticsearch数据
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: cloudxr-kibana
    environment:
      - elasticsearch.hosts=http://127.0.0.1:9200
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - cloudxr
    ports:
      - "45601:5601"
    depends_on:
      - elasticsearch

deploy/go-stash/etc/config.yaml:
Clusters:
  - Input:
      Kafka:
        Name: gostash
        Brokers:
          - "cloudxr-kafka:9092"
        Topics:
          - cloudxr-log
        Group: pro
        Consumers: 16
    Filters:
      - Action: drop
        Conditions:
          - Key: k8s_container_name
            Value: "-rpc"
            Type: contains
          - Key: level
            Value: info
            Type: match
            Op: and
      - Action: remove_field
        Fields:
          #- message
          - _source
          - _type
          - _score
          - _id
          - "@version"
          - topic
          - index
          - beat
          - docker_container
          - offset
          - prospector
          - source
          - stream
          - "@metadata"
      - Action: transfer
        Field: message
        Target: data
    Output:
      ElasticSearch:
        Hosts:
          - "http://127.0.0.1:9200"
        Index: "cloudxr-{{yyyy-MM-dd}}"

**Comment by Mikaelemmmm** [comment]
这个应该是kafka不可用导致的，你改了kafka端口，kafka配置中监听那个配置也要改

**Comment by gocpplua** [comment]
> 这个应该是kafka不可用导致的，你改了kafka端口，kafka配置中监听那个配置也要改
好的， 我修改成为如下就行了

Clusters:
  - Input:
      Kafka:
        Name: gostash
        Brokers:
          - "cloudxr-kafka:49092"
        Topics:
          - cloudxr-log
        Group: pro
        Consumers: 16
    Filters:
      - Action: drop
        Conditions:
          - Key: k8s_container_name
            Value: "-rpc"
            Type: contains
          - Key: level
            Value: info
            Type: match
            Op: and
      - Action: remove_field
        Fields:
          # - message
          - _source
          - _type
          - _score
          - _id
          - "@version"
          - topic
          - index
          - beat
          - docker_container
          - offset
          - prospector
          - source
          - stream
          - "@metadata"
      - Action: transfer
        Field: message
        Target: data
    Output:
      ElasticSearch:
        Hosts:
          - "http://cloudxr-elasticsearch:9200"
        Index: "cloudxr-{{yyyy-MM-dd}}"
