### ISSUE TITLE
elasticsearch 启动占用cpu过高

### ISSUE THREAD

**Issue by Jacktbak** [Mikaelemmmm/go-zero-looklook#62]
你好， 第一步用docker-compose启动所有镜像后， 其中elasticsearch 这个镜像cpu占用达到了189%，是配置不对吗？                       
 PID   USER      PR  NI    VIRT     RES        SHR S     %CPU %MEM     TIME+ COMMAND                                                                                      
 4145 lightho+  20   0 3121992 646488  22416 S 189.7 16.7   0:09.52 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -

**Comment by Mikaelemmmm** [comment]
es本身就比较重，相对比较占用机器
