### ISSUE TITLE
docker部署出错 dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:39899->127.0.0.11:53: i/o timeout

### ISSUE THREAD

**Issue by ShaPoHun** [Mikaelemmmm/go-zero-looklook#65]
启动报错，docker中日志：
```
looklook         | 19:58:53: prep: go build -o data/server/payment-rpc  -v app/payment/cmd/rpc/payment.go
looklook         | go: downloading github.com/zeromicro/go-zero v1.3.4
looklook         | go: downloading google.golang.org/grpc v1.46.2
looklook         | go: downloading github.com/zeromicro/go-queue v1.1.5
looklook         | go: downloading google.golang.org/protobuf v1.28.0
looklook         | go: downloading github.com/pkg/errors v0.9.1
looklook         | go: downloading github.com/jinzhu/copier v0.3.2
looklook         | go: downloading github.com/Masterminds/squirrel v1.5.2
looklook         | go: downloading github.com/sony/sonyflake v1.0.0
looklook         | go: downloading github.com/shopspring/decimal v1.3.1
looklook         | app/payment/model/thirdPaymentModel.go:10:2: github.com/Masterminds/squirrel@v1.5.2: Get "https://goproxy.cn/github.com/%21masterminds/squirrel/@v/v1.5.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:35491->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/internal/logic/getPaymentBySnLogic.go:11:2: github.com/jinzhu/copier@v0.3.2: Get "https://goproxy.cn/github.com/jinzhu/copier/@v/v0.3.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:35491->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/internal/logic/createPaymentLogic.go:11:2: github.com/pkg/errors@v0.9.1: Get "https://goproxy.cn/github.com/pkg/errors/@v/v0.9.1.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:39899->127.0.0.11:53: i/o timeout
looklook         | common/tool/coinconvert.go:3:8: github.com/shopspring/decimal@v1.3.1: Get "https://goproxy.cn/github.com/shopspring/decimal/@v/v1.3.1.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:35491->127.0.0.11:53: i/o timeout
looklook         | common/uniqueid/uniqueid.go:4:2: github.com/sony/sonyflake@v1.0.0: Get "https://goproxy.cn/github.com/sony/sonyflake/@v/v1.0.0.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:35491->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/internal/svc/serviceContext.go:4:2: github.com/zeromicro/go-queue@v1.1.5: Get "https://goproxy.cn/github.com/zeromicro/go-queue/@v/v1.1.5.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:39899->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/payment.go:13:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/internal/logic/createPaymentLogic.go:12:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/payment.go:14:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/model/thirdPaymentModel_gen.go:15:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/internal/config/config.go:4:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/model/thirdPaymentModel_gen.go:17:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/internal/svc/serviceContext.go:8:2: github.com/zeromicro/go-zero@v1.3.4: Get 
"https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/model/thirdPaymentModel_gen.go:19:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/payment.go:15:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/payment.go:16:2: google.golang.org/grpc@v1.46.2: Get "https://goproxy.cn/google.golang.org/grpc/@v/v1.46.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/pb/payment.pb.go:12:2: google.golang.org/grpc@v1.46.2: Get "https://goproxy.cn/google.golang.org/grpc/@v/v1.46.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/payment.go:17:2: google.golang.org/grpc@v1.46.2: Get "https://goproxy.cn/google.golang.org/grpc/@v/v1.46.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/pb/payment.pb.go:13:2: google.golang.org/grpc@v1.46.2: Get "https://goproxy.cn/google.golang.org/grpc/@v/v1.46.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/pb/payment.pb.go:14:2: google.golang.org/protobuf@v1.28.0: Get "https://goproxy.cn/google.golang.org/protobuf/@v/v1.28.0.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:39899->127.0.0.11:53: i/o timeout
looklook         | app/payment/cmd/rpc/pb/payment.pb.go:15:2: google.golang.org/protobuf@v1.28.0: Get "https://goproxy.cn/google.golang.org/protobuf/@v/v1.28.0.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:39899->127.0.0.11:53: i/o timeout
looklook         | exit status 1
```

**Comment by ShaPoHun** [comment]
my environmental problems

**Comment by cansustar** [comment]
Hi, I encountered the same problem while studying this project, how did you solve it?

**Comment by liushuai05** [comment]
> 启动报错，docker中日志：
> 
> ```
> looklook         | 19:58:53: prep: go build -o data/server/payment-rpc  -v app/payment/cmd/rpc/payment.go
> looklook         | go: downloading github.com/zeromicro/go-zero v1.3.4
> looklook         | go: downloading google.golang.org/grpc v1.46.2
> looklook         | go: downloading github.com/zeromicro/go-queue v1.1.5
> looklook         | go: downloading google.golang.org/protobuf v1.28.0
> looklook         | go: downloading github.com/pkg/errors v0.9.1
> looklook         | go: downloading github.com/jinzhu/copier v0.3.2
> looklook         | go: downloading github.com/Masterminds/squirrel v1.5.2
> looklook         | go: downloading github.com/sony/sonyflake v1.0.0
> looklook         | go: downloading github.com/shopspring/decimal v1.3.1
> looklook         | app/payment/model/thirdPaymentModel.go:10:2: github.com/Masterminds/squirrel@v1.5.2: Get "https://goproxy.cn/github.com/%21masterminds/squirrel/@v/v1.5.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:35491->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/internal/logic/getPaymentBySnLogic.go:11:2: github.com/jinzhu/copier@v0.3.2: Get "https://goproxy.cn/github.com/jinzhu/copier/@v/v0.3.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:35491->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/internal/logic/createPaymentLogic.go:11:2: github.com/pkg/errors@v0.9.1: Get "https://goproxy.cn/github.com/pkg/errors/@v/v0.9.1.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:39899->127.0.0.11:53: i/o timeout
> looklook         | common/tool/coinconvert.go:3:8: github.com/shopspring/decimal@v1.3.1: Get "https://goproxy.cn/github.com/shopspring/decimal/@v/v1.3.1.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:35491->127.0.0.11:53: i/o timeout
> looklook         | common/uniqueid/uniqueid.go:4:2: github.com/sony/sonyflake@v1.0.0: Get "https://goproxy.cn/github.com/sony/sonyflake/@v/v1.0.0.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:35491->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/internal/svc/serviceContext.go:4:2: github.com/zeromicro/go-queue@v1.1.5: Get "https://goproxy.cn/github.com/zeromicro/go-queue/@v/v1.1.5.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:39899->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/payment.go:13:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/internal/logic/createPaymentLogic.go:12:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/payment.go:14:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/model/thirdPaymentModel_gen.go:15:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/internal/config/config.go:4:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/model/thirdPaymentModel_gen.go:17:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/internal/svc/serviceContext.go:8:2: github.com/zeromicro/go-zero@v1.3.4: Get 
> "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/model/thirdPaymentModel_gen.go:19:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/payment.go:15:2: github.com/zeromicro/go-zero@v1.3.4: Get "https://goproxy.cn/github.com/zeromicro/go-zero/@v/v1.3.4.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/payment.go:16:2: google.golang.org/grpc@v1.46.2: Get "https://goproxy.cn/google.golang.org/grpc/@v/v1.46.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/pb/payment.pb.go:12:2: google.golang.org/grpc@v1.46.2: Get "https://goproxy.cn/google.golang.org/grpc/@v/v1.46.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/payment.go:17:2: google.golang.org/grpc@v1.46.2: Get "https://goproxy.cn/google.golang.org/grpc/@v/v1.46.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/pb/payment.pb.go:13:2: google.golang.org/grpc@v1.46.2: Get "https://goproxy.cn/google.golang.org/grpc/@v/v1.46.2.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:57976->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/pb/payment.pb.go:14:2: google.golang.org/protobuf@v1.28.0: Get "https://goproxy.cn/google.golang.org/protobuf/@v/v1.28.0.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:39899->127.0.0.11:53: i/o timeout
> looklook         | app/payment/cmd/rpc/pb/payment.pb.go:15:2: google.golang.org/protobuf@v1.28.0: Get "https://goproxy.cn/google.golang.org/protobuf/@v/v1.28.0.zip": dial tcp: lookup goproxy.cn on 127.0.0.11:53: read udp 127.0.0.1:39899->127.0.0.11:53: i/o timeout
> looklook         | exit status 1
> ```

大佬我也遇到了类似的问题,请问你是怎么解决的呢,方便透露一下嘛
