### ISSUE TITLE
关于token过期自动刷新的问题

### ISSUE THREAD

**Issue by chaozwn** [Mikaelemmmm/go-zero-looklook#68]
今天在群里问了下万总，go zero自带的jwt认证是不会实现自动刷新token的，但是我看你好像没有go zero自带的Auth Handler，而是使用自己的token认证，不知道是怎么实现token的自动刷新的。

**Comment by chaozwn** [comment]
中间件NewCommonJwtAuthMiddleware似乎也没有用到

**Comment by Mikaelemmmm** [comment]
可能我在文档描述错了，是两个secret 会自动，token刷新要自己实现了

**Comment by chaozwn** [comment]
> 可能我在文档描述错了，是两个secret 会自动，token刷新要自己实现了

这边我建议，就不要使用go zero自带的jwt认证了，我们自己去实现一个auth middleware，然后可以实现token自动刷新，和logout, jwt传递数据只保存一个userId,然后userId的用户信息放在redis当中，每次token使用重新重置时间。

**Comment by Mikaelemmmm** [comment]
也可以的 ，自己写个中间件就行了
