### ISSUE TITLE
CI问题 | 大神可不可以使用Drone整合gitlab与harbor

### ISSUE THREAD

**Issue by Holyson** [Mikaelemmmm/go-zero-looklook#69]
jenkins对于开发者，服务器压力较大，跑在docker中一个jenkins 至少吃1个G内存
使用drone为100MB，希望大神也可以出一个

**Comment by waltcow** [comment]
可以尝试 github action 构建镜像 ，push 到aliyun 的私有镜像仓库

**Comment by Mikaelemmmm** [comment]
这个目前还没计划，后面看看

**Comment by Holyson** [comment]
> 这个目前还没计划，后面看看

3q
