### ISSUE TITLE
win11无法收集日志数据。

### ISSUE THREAD

**Issue by xiao-linxin** [Mikaelemmmm/go-zero-looklook#75]
win11系统无法获取得到日志，要改什么配置吗？求帮忙~

![file](https://cdn.learnku.com/uploads/images/202208/05/41893/Ydjd86rULm.png!large)

![Go](https://cdn.learnku.com/uploads/images/202208/05/41893/jsmVDWXMos.png!large)

![Go](https://cdn.learnku.com/uploads/images/202208/05/41893/7pkdaiurSd.png!large)

![Go](https://cdn.learnku.com/uploads/images/202208/05/41893/JpPSbK48oo.png!large)

![Go](https://cdn.learnku.com/uploads/images/202208/05/41893/A7NgLJwBbq.png!large)

系统参数：
版本	Windows 11 专业版
版本	21H2
操作系统版本	22000.795

**Comment by Mikaelemmmm** [comment]
先启动 kafka在启动go-stash，如果还不行就检查一下filebeat配置文件中配置的docker容器日志的位置，这个东西不同系统位置也有不一样的

**Comment by xiao-linxin** [comment]
配置啥也不用改，启动多几次就可以了。

**Comment by xiao-linxin** [comment]
配置是对的，启动多几次。然后 create an index pattern 页面等一下，再输入 looklook-* 就解决了。
