### ISSUE TITLE
请教一下，模板支持外部变量不？

### ISSUE THREAD

**Issue by weiailuxueqi** [Mikaelemmmm/go-zero-looklook#77]
![image](https://user-images.githubusercontent.com/27498426/184076301-b4a77577-90d7-464c-9621-84d5da562f5a.png)

如题，支持外部变量不，或者有什么方式可以在模板里头定义变量，如果当前table含有该变量的字段名时，才生成相应的代码。例如：当有version字段时，就生成版本号更新操作的代码。

**Comment by Mikaelemmmm** [comment]
变量目前是来自 go-zero项目下的goctl代码中传递过来的，如果想传递自己变量可能要fork后修改

**Comment by weiailuxueqi** [comment]
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/27498426/184339160-23b17672-2e65-4fb4-b36e-cc3cd0ec0f46.png">
@Mikaelemmmm 大兄弟，能告诉我下这个错误是因为啥导致的吗，格式跟你也差不多啊。。。。

**Comment by Mikaelemmmm** [comment]
> 

已经提示很清楚啦，重复定义了
