### ISSUE TITLE
请问你的项目中有进行接口鉴权的操作吗？

### ISSUE THREAD

**Issue by lightnine** [Mikaelemmmm/go-zero-looklook#79]
我看到你使用的jwt，但是这个只是做了认证。对于接口权限这块有相关的解决方案吗？

**Comment by Mikaelemmmm** [comment]
> 

如果你是想问rbac的，可以用casbin
如果你想有状态的token，可以用redis+jwt

这两个都可以自己写中间件解决你的问题哈
