### ISSUE TITLE
want to reuse common code and template

### ISSUE THREAD

**Issue by william-best** [Mikaelemmmm/go-zero-looklook#86]
It is a wonderful example for go-zero.  And I want  to reuse the common code, could you share the common code as a single git.

Want to reuse:
1. common code
2. template （especially db related)

my suggestion
1. user a significative name not looklook
2. give a shell or python script to install the template from git

**Comment by Mikaelemmmm** [comment]
这个获取你可以自己抽离一个独立库使用“go get”导入即可

**Comment by Mikaelemmmm** [comment]
You can get this by pulling out a separate library and importing it using "go get".
