### ISSUE TITLE
sql问题

### ISSUE THREAD

**Issue by sapolang** [Mikaelemmmm/go-zero-looklook#87]
`create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,

为何所有字段都有默认值， 这个是定好的表设计规范，还是...

**Comment by Mikaelemmmm** [comment]
是的  内部定好的规范
