### ISSUE TITLE
关于微服务仓库管理问题

### ISSUE THREAD

**Issue by cexll** [Mikaelemmmm/go-zero-looklook#88]
因为本项目是微服务出发 那么在公司内或者开发 每个项目/服务是分开 一个服务一个git仓库好还是在一个仓库好

在其他地方看到 说微服务项目每个服务就应该分开 一个git仓库就是一个服务

**Comment by Mikaelemmmm** [comment]
这个每个公司情况不一样，可以集中一个仓库，可以分开 这个根据公司实际情况来，各有各的好处，也有各自的缺点

**Comment by cexll** [comment]
> 这个每个公司情况不一样，可以集中一个仓库，可以分开 这个根据公司实际情况来，各有各的好处，也有各自的缺点

感谢回答

我觉得集中一个仓库有个优势就是可以统一管理代码审查 开发新功能fork一个仓库开发增加就行了 提交代码就通过pr方式比较方便管理一点 但是集中可能对于代码泄露 或者代码审查需要一个人来抽出时间管理比较麻烦
