### ISSUE TITLE
前后端分离开发流程怎么走？SQL变更流程怎么走？

### ISSUE THREAD

**Issue by trealma** [Mikaelemmmm/go-zero-looklook#89]
通常需求确定了得文档协议先行，那那需求定了直接写api生成swag给前端？写proto生成client库给后端？

sql变更应该有版本记录，历史变更sql怎么维护？

测试测接口只需要测api，无需测rpc了吧

**Comment by Mikaelemmmm** [comment]
这个属于公司内部规范了，每个公司都有自己规定
sql变更可以有change log 追踪，跟前端定好api接口文档就好了
