### ISSUE TITLE
没有处理 MsgPaySuccessNotifyUser 类型的asynq消息

### ISSUE THREAD

**Issue by ch0ngsheng** [Mikaelemmmm/go-zero-looklook#90]
https://github.com/Mikaelemmmm/go-zero-looklook/blob/97880dcf47be9cfa7a1bf9c8602b60b8daf345f9/app/mqueue/cmd/job/internal/logic/routes.go#L34

这里是不是也要注册 MsgPaySuccessNotifyUser 类型消息的handler？

**Comment by Mikaelemmmm** [comment]
是的
