### ISSUE TITLE
About looklook payment-api service start failed

### ISSUE THREAD

**Issue by XiaoLiu1020** [Mikaelemmmm/go-zero-looklook#91]
Any of Other looklook service can start success  but payment-api
just see this prometheus target
![image](https://user-images.githubusercontent.com/49826681/203931154-a2f6cac7-a473-45ad-9a1f-abbb48dd1799.png)

All of my other docker also up 
I can see the error in the looklook container(`docker logs looklook | grep 'payment-api' - C 10`)
```shell
15:43:19: prep: go build -o data/server/payment-rpc  -v app/payment/cmd/rpc/payment.go
>> done (1.202620141s)
15:43:19: prep: go build -o data/server/payment-api  -v app/payment/cmd/api/payment.go
15:43:19: daemon: ./data/server/payment-rpc -f app/payment/cmd/rpc/etc/payment.yaml
>> starting...
15:43:19: prep: go build -o data/server/payment-api  -v app/payment/cmd/api/payment.go
verifying github.com/wechatpay-apiv3/wechatpay-go@v0.2.9: zip: not a valid zip file
exit status 1
15:43:19: prep: go build -o data/server/order-rpc  -v app/order/cmd/rpc/order.go
15:43:19: daemon: ./data/server/payment-rpc -f app/payment/cmd/rpc/etc/payment.yaml
Starting rpc server at 0.0.0.0:2002...
15:43:21: prep: go build -o data/server/order-rpc  -v app/order/cmd/rpc/order.go
>> done (1.527597833s)

```

you can see the problem about wechatpay-go package 
How I can solve this?

**Comment by Mikaelemmmm** [comment]
It may be the version of this library that is causing the problem, as it has been fine before, I'll check it out later

**Comment by Mikaelemmmm** [comment]
I've tested this several times and it works fine on my end. It looks like the "wechat-pay" dependency is downloading incorrectly due to the network, you can manually download the dependency once inside the container and try it again

**Comment by Mikaelemmmm** [comment]
> Any of Other looklook service can start success but payment-api just see this prometheus target ![image](https://user-images.githubusercontent.com/49826681/203931154-a2f6cac7-a473-45ad-9a1f-abbb48dd1799.png)
> 
> All of my other docker also up I can see the error in the looklook container(`docker logs looklook | grep 'payment-api' - C 10`)
> 
> ```shell
> 15:43:19: prep: go build -o data/server/payment-rpc  -v app/payment/cmd/rpc/payment.go
> >> done (1.202620141s)
> 15:43:19: prep: go build -o data/server/payment-api  -v app/payment/cmd/api/payment.go
> 15:43:19: daemon: ./data/server/payment-rpc -f app/payment/cmd/rpc/etc/payment.yaml
> >> starting...
> 15:43:19: prep: go build -o data/server/payment-api  -v app/payment/cmd/api/payment.go
> verifying github.com/wechatpay-apiv3/wechatpay-go@v0.2.9: zip: not a valid zip file
> exit status 1
> 15:43:19: prep: go build -o data/server/order-rpc  -v app/order/cmd/rpc/order.go
> 15:43:19: daemon: ./data/server/payment-rpc -f app/payment/cmd/rpc/etc/payment.yaml
> Starting rpc server at 0.0.0.0:2002...
> 15:43:21: prep: go build -o data/server/order-rpc  -v app/order/cmd/rpc/order.go
> >> done (1.527597833s)
> ```
> 
> you can see the problem about wechatpay-go package How I can solve this?

I've tested this several times and it works fine on my end. It looks like the "wechat-pay" dependency is downloading incorrectly due to the network, you can manually download the dependency once inside the container and try it again
