### ISSUE TITLE
有api接口文档的json文件吗？

### ISSUE THREAD

**Issue by GrandeLai** [Mikaelemmmm/go-zero-looklook#96]

**Comment by Mikaelemmmm** [comment]
可以使用goctl api doc命令生成markdown文档，或者使用https://github.com/zeromicro/goctl-swagger 这个生成json

**Comment by Mikaelemmmm** [comment]
> _No description provided._

可以使用goctl api doc命令生成markdown文档，或者使用https://github.com/zeromicro/goctl-swagger 这个生成json
