### ISSUE TITLE
windows11 环境修改代码后不自动编译

### ISSUE THREAD

**Issue by zhouqunjie-cs** [Mikaelemmmm/go-zero-looklook#97]
windows11 环境修改代码后不自动编译，centos环境正常
cenots:
![image](https://user-images.githubusercontent.com/57168982/215937954-242e6560-a643-420b-ab53-d5848a527dd6.png)
win11:
docker 进程都一样
![image](https://user-images.githubusercontent.com/57168982/215938058-816b155f-67ef-48d5-95ac-c8fdc6b08c87.png)
![image](https://user-images.githubusercontent.com/57168982/215938137-b0fc0bc4-3ddd-432b-954e-83f1be125af5.png)

是否需要在ide配置？

**Comment by 123zzz** [comment]
+1 , windows 10也是。其他都正常

**Comment by Mikaelemmmm** [comment]
这个是 modd 对windows的支持有点有问题
